repos:
-  repo: https://github.com/pre-commit/pre-commit-hooks
   rev: v2.0.0
   hooks:
   -  id: check-json
   -  id: check-merge-conflict
   -  id: check-xml
   -  id: check-yaml
   -  id: detect-private-key
-  repo: git@github.com:coyainsurance/pre-commit-scalafmt.git
   sha: master
   hooks:
   -  id: scalafmt
      args: [-t ]
-  repo: local
   hooks:
   -  id: scalastyle
      name: scalastyle
      entry: scalastyle --config scalastyle-config.xml
      language: system
      files: \.(scala|sbt)$
      types: [file, text]
